kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: nvidia-mutlimodal-rag
  context: ./RAG/examples/advanced_rag/multimodal_rag
  dockerfile: ./src/chain_server/Dockerfile

spec:
  operator: kuberay
  rayVersion: "2.3.0"

  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
        - name: ray-head
          image: nvidia-mutlimodal-rag
          resources:
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1

  workerGroupSpecs:
  - groupName: chain-server
    replicas: 1
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: nvidia-mutlimodal-rag
          resources:
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
          ports:
          - containerPort: 8081
          env:
          - name: EXAMPLE_PATH
            value: "advanced_rag/multimodal_rag"
          - name: APP_LLM_MODELNAME
            value: ${APP_LLM_MODELNAME:-"meta/llama3-8b-instruct"}
          - name: APP_LLM_MODELENGINE
            value: nvidia-ai-endpoints
          - name: APP_LLM_SERVERURL
            value: ${APP_LLM_SERVERURL:-""}
          - name: APP_EMBEDDINGS_MODELNAME
            value: ${APP_EMBEDDINGS_MODELNAME:-nvidia/nv-embedqa-e5-v5}
          - name: APP_EMBEDDINGS_MODELENGINE
            value: ${APP_EMBEDDINGS_MODELENGINE:-nvidia-ai-endpoints}
          - name: APP_EMBEDDINGS_SERVERURL
            value: ${APP_EMBEDDINGS_SERVERURL:-""}
          - name: APP_TEXTSPLITTER_MODELNAME
            value: Snowflake/snowflake-arctic-embed-l
          - name: APP_TEXTSPLITTER_CHUNKSIZE
            value: "510"
          - name: APP_TEXTSPLITTER_CHUNKOVERLAP
            value: "200"
          - name: NVIDIA_API_KEY
            value: ${NVIDIA_API_KEY}
          - name: APP_RETRIEVER_TOPK
            value: "4"
          - name: APP_RETRIEVER_SCORETHRESHOLD
            value: "0.25"
          - name: APP_VECTORSTORE_URL
            value: "http://milvus:19530"
          - name: APP_VECTORSTORE_NAME
            value: "milvus"
          - name: COLLECTION_NAME
            value: ${COLLECTION_NAME:-multimodal_rag}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector:4317"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
          - name: ENABLE_TRACING
            value: "false"
          - name: LOGLEVEL
            value: ${LOGLEVEL:-INFO}

  - groupName: rag-playground
    replicas: 1
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: nvidia-mutlimodal-rag
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
          ports:
          - containerPort: 8090
          env:
          - name: APP_SERVERURL
            value: "http://chain-server"
          - name: APP_SERVERPORT
            value: "8081"
          - name: APP_MODELNAME
            value: ${APP_LLM_MODELNAME:-"meta/llama3-8b-instruct"}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector:4317"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
          - name: ENABLE_TRACING
            value: "false"
