apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: nvidia-multimodal-rag
spec:
  rayVersion: "2.3.0"
  enableInTreeAutoscaling: true
  
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
        - name: ray-head
          image: nvidia-multimodal-rag
          resources:
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
          
  workerGroupSpecs:
  - groupName: chain-server
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: nvidia-multimodal-rag
          resources:
            limits:
              cpu: 8
              memory: 32Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 8 
              memory: 32Gi
              nvidia.com/gpu: 1
          ports:
          - containerPort: 8081
          env:
          - name: EXAMPLE_PATH
            value: "advanced_rag/multimodal_rag"
          - name: APP_LLM_MODELNAME
            value: "meta/llama3-8b-instruct"
          - name: APP_LLM_MODELENGINE
            value: "nvidia-ai-endpoints"
          - name: APP_EMBEDDINGS_MODELNAME
            value: "nvidia/nv-embedqa-e5-v5"
          - name: APP_EMBEDDINGS_MODELENGINE
            value: "nvidia-ai-endpoints"
          - name: APP_TEXTSPLITTER_MODELNAME
            value: "Snowflake/snowflake-arctic-embed-l"
          - name: APP_TEXTSPLITTER_CHUNKSIZE
            value: "510"
          - name: APP_TEXTSPLITTER_CHUNKOVERLAP
            value: "200"
          - name: APP_RETRIEVER_TOPK
            value: "4"
          - name: APP_RETRIEVER_SCORETHRESHOLD
            value: "0.25"
          - name: APP_VECTORSTORE_URL
            value: "http://milvus:19530"
          - name: APP_VECTORSTORE_NAME
            value: "milvus"
          - name: COLLECTION_NAME
            value: "multimodal_rag"
          - name: LOGLEVEL
            value: "INFO"
          
  - groupName: rag-playground
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: nvidia-multimodal-rag
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
          ports:
          - containerPort: 8090
          env:
          - name: APP_SERVERURL
            value: "http://chain-server"
          - name: APP_SERVERPORT
            value: "8081"
          - name: APP_MODELNAME
            value: "meta/llama3-8b-instruct"